# Generated by Django 4.1.2 on 2022-10-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='Creation date')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('answered', models.BooleanField(verbose_name='Answered?')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
    ]
